### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Mikejmnez** [malmans2/oceanspy#287]
I will be working on a new release, long overdue, in the next couple of days. This will make it easier to use the new oceanspy features (specially PRs #281 #284 and #285) say on Sciserver, without needing a pip install from the GH repo.

**Comment by malmans2** [comment]
You might need my approval to issue a new release on pypi. I'm pretty sure the releasing procedure we are using is quite old. If you can wait until Monday (it's a bank holiday in Italy) I'll give you the permissions to release and I will also update the procedure (in the future, you will only have to make a release on github and both pypi and conda forge will also issue a release with the right version).

**Comment by Mikejmnez** [comment]
Great! It is quite old. `bump2version` hasn't been updated in like two years. I'll wait until next week then.

**Comment by malmans2** [comment]
Looks like issues with xesmf showed up when #288 was merged into main. Not sure why, it was ok a few hours ago: https://github.com/hainegroup/oceanspy/actions/runs/3675826523

Do you guys have time to take a look?

**Comment by Mikejmnez** [comment]
Sure, I'll take a look. 
I also noticed that the documentation hasn't updated to show any changes you did in your PR.

**Comment by malmans2** [comment]
Good catch! RTD should be OK now, it was still pointing to "master"

**Comment by Mikejmnez** [comment]
@malmans2 I still don't see the new updated documentation. There was a build based on your PR #288 but it appears to have created a new version based on that PR. See the two cases below (screenshot from my laptop) :

1. ## Version: Latest
This is the screenshot when I go directly to the oceanspy documentation. Here, the `Contributing` (and other sections like `People`) remain as before, unchanged.

<img width="600" alt="latest" src="https://user-images.githubusercontent.com/8241481/207158800-29f0f99e-0f00-4e83-b9ca-329ab2e54f14.png">


2. ## Version: 288
In this version of the documentation, 
To see this particular version, I have to click on the link you supply on your comment in PR #288 . The link is:
https://oceanspy--288.org.readthedocs.build/en/288/contributing.html#deploying

<img width="600" alt="v288" src="https://user-images.githubusercontent.com/8241481/207158870-59a4d080-a9f6-4b53-8874-99a5426b0b27.png">



I synced my fork and noticed there are two untracked files resulting from that PR #288. Here's the snapshot from my command line:

<img width="300" alt="snapshot" src="https://user-images.githubusercontent.com/8241481/207159595-b7f37582-5834-49ae-b52c-cc80f7b074ed.png">


These were not there before in my local repository. I will stage them, create a new PR and maybe this will help update the documentation. Particularly resolve #253

**Comment by malmans2** [comment]
This looks good to me (I only edited the Deploying section at the bottom): https://oceanspy.readthedocs.io/en/latest/contributing.html

Maybe you have to refresh or clear your browser cache?

**Comment by Mikejmnez** [comment]
Ok, that could be it...

**Comment by Mikejmnez** [comment]
Great, it did! I did have to refresh a couple of times. And actually, the binder is the correct one so #250 can now be closed! I am a little annoyed though...

**Comment by Mikejmnez** [comment]
@malmans2 what do you suggest to do with all the untracked documentation files (`docs/datasets.rst` and `docs/generated/`)?

**Comment by malmans2** [comment]
I think those dir and file should go back in the  .gitignore as they are generated each time we compile the documentation. I updated the  .gitignore and I inadvertently removed them.

**Comment by malmans2** [comment]
mmm, https://anaconda.org/conda-forge/esmpy was released on conda-forge a few hours ago.
Must be related to the issues we are seeing (BTW, if pytest fails the workflow will not proceed with the release on PyPI)

**Comment by Mikejmnez** [comment]
OK. So we need to fix this pytest fail before the release. I'll work on this test fail today then. After fixing it, will issue a new release

**Comment by Mikejmnez** [comment]
Fixed failing tests by pining esmf, see PR #292 and issue #291. 
I am releasing a new version of oceanspy and thus will close this issue.

**Comment by malmans2** [comment]
The release on PyPI did not go through yesterday because you forgot to delete the tag when you deleted the release.
There were also a couple of typos in the workflow.

All fixed now and v0.3.0 is on PyPI: https://pypi.org/project/oceanspy/#history

`conda-forge` should also open a PR soon

From now on releasing is just a matter of creating a new release on GH.

**Comment by Mikejmnez** [comment]
Great! I didn't realize tags needed to be deleted but is all learned now! Thanks a lot @malmans2 !

**Comment by malmans2** [comment]
There's just one thing left: the conda-forge release.
Can you handle it please so you'll be able to do it in the future?
Here is the PR: https://github.com/conda-forge/oceanspy-feedstock/pull/9

If you need support to merge the PR, Filipe Fernandes is the conda-forge guru (github tag is `@ocefpaf`)

**Comment by Mikejmnez** [comment]
Sure!
